# Generated by Django 4.2.7 on 2026-07-28 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_restaurant_pincode_restaurant_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='google_maps_link',
            field=models.TextField(blank=True),
        ),
    ]
