# Generated by Django 4.2.7 on 2026-08-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0008_restaurant_reserved_tables_restaurant_total_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ingredients', 'Ingredients & Raw Materials'), ('Staff Salary', 'Staff Salary & Wages'), ('Rent', 'Rent & Real Estate'), ('Utilities', 'Electricity, Gas & Water'), ('Marketing', 'Marketing & Promotions'), ('Maintenance', 'Maintenance & Repairs'), ('Other', 'Other Operating Expenses')], default='Ingredients', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='restaurants.restaurant')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
