# Generated by Django 4.2.30 on 2026-07-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='swiggy_food_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
